---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: template
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: akmods
    base: main
    install:
      - v4l2loopback  # optional, just an example
      - xone
    nvidia-driver: "nvidia-open"  # or "nvidia-open" for newer GPUs

  # Disable and mask zram service
  - type: systemd
    system:
      disabled:
        - zram-generator@zram0.service
      masked:
        - zram-generator@zram0.service

  # Copy zswap configuration file
  - type: files
    files:
      - source: system
        destination: /

  - type: kargs
    kargs:
      - zswap.enabled=1
      - zswap.compressor=zstd
      - zswap.max_pool_percent=25
      - zswap.zpool=z3fold

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - alacritty
        - micro
        - starship
        - tmux
        - zsh
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: gnome-extensions
    install:
      - 6099  # https://extensions.gnome.org/extension/6099/paperwm/

  - type: brew
    brew-analytics: false
    nofile-limits: true

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - com.bitwarden.desktop
          - com.slack.Slack
          - com.vivaldi.Vivaldi
          - com.getpostman.Postman
          - com.visualstudio.code
          - com.jetbrains.Rider
          - md.obsidian.Obsidian
          - com.github.tchx84.Flatseal
          - io.github.flattool.Warehouse
          - io.missioncenter.MissionCenter
          - com.github.rafostar.Clapper
          - org.gnome.Loupe
          - org.gnome.Extensions
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully